export const UAE = [
  {
    nameAR: "الإمارات العربية المتحدة",
    url: "",
    nameEN: "UAE",
    nameRU: "Объединенные Арабские Эмираты",
    src: "/images/UAE/1.webp",
    descriptionAR:
      "هي دولة عربية اتحادية تقع في شمال شرق ش به الجزيرة العربية في جَنوب غرب قارة آ س يا تطل على الشاطئ الجَنوبي للخليج العربي لها حدود بحرية مشتركة من الشمال الغربي مع دولة قطر ومن الشمال مع الخليج العربي ومن الغرب حدود برية وبحرية مع المملكة العربية السعودية ومن الجَنوب الشرقي مع سلطنة عُمان . ا إ لإمارات هي سابع آكبر منتج للنفط في العالم . وتمتلك واحداً من آكثر الاقتصادات نمواً في غرب آ س يا، إ ان اقتصاد دولة ا إ لإمارات يحتل المرتبة 22 على مس توى العالم في آسعار الصرف في السوق وهي ثاني آكبر دولة في القوة الشرائية ترجع تسمية ا إ لإمارات العربية المتحدة إ الى ا إ لإمارات الس بع التي شكلت اتحاداً فيما بينها، وهي : إ امارة آبوظ ب وإامارة دبي وإامارة عجمان وإامارة الشارقة وإامارة ر آس الخيمة وإامارة آم القيوين وإامارة الفجيرة",
    descriptionEN:
      "It is a federal Arab state located in the northeast of the Arabian Peninsula in the southwest of the continent of Asia, overlooking the southern shore of the Arabian Gulf. It has maritime borders. Shared to the northwest with the State of Qatar, to the north with the Arabian Gulf, to the west, land and sea borders with the Kingdom of Saudi Arabia, and to the southeast. With the Sultanate of Oman. The UAE is the seventh largest oil producer in the world. It has one of the most developed economies in West Asia, but the economy of the UAE occupies It ranks 22nd in the world in market exchange rates and is the second largest country in purchasing power. The name of the United Arab Emirates is due to the Emirates. The seven that formed a union among themselves, namely: the Emirate of Abu Dhabi, the Emirate of Dubai, the Emirate of Ajman, the Emirate of Sharjah, the Emirate of Ras Al Khaimah, the Emirate of Umm Al Quwain, and the Emirate of Fujairah.",
    descriptionRU:
      "Это федеративное арабское государство, расположенное на северо-востоке Аравийского полуострова на юго-западе азиатского континента, с видом на южный берег Персидского залива. Оно имеет морские границы. Разделяется на северо-западе с Государством Катар, на севере с Персидским заливом, на западе сухопутные и морские границы с Королевством Саудовская Аравия и на юго-востоке. С Султанатом Оман. ОАЭ являются седьмым по величине производителем нефти в мире. У него одна из самых развитых экономик в Западной Азии, но экономика ОАЭ занимает Она занимает 22-е место в мире по рыночным курсам валют и является второй по величине страной по покупательной способности. Название Объединенные Арабские Эмираты связано с Эмиратами. Семь, которые образовали союз между собой, а именно: Эмират Абу-Даби, Эмират Дубай, Эмират Аджман, Эмират Шарджа, Эмират Рас-эль-Хайма, Эмират Умм-эль-Кувейн и Эмират Фуджейра.",
  },

  {
    nameAR: "أبوظبي",
    url: "",
    nameEN: "Abu Dhabi",
    nameRU: "Абу-Даби",
    src: "/images/UAE/12.webp",
    descriptionAR:
      "تقع عاصمة دولة الإمارات العربية المتحدة على جزيرة أبو ظبي، وتمتد إلى أكبر الإمارات السبع، وتشمل البر الرئيسي والجزر. مدينة أبو ظبي هي عاصمة الدولة الاتحادية، كما أنها تمتلك أكبر خط ساحلي مقارنة بالإمارات الأخرى، والذي يمتد من إمارة دبي في الشمال إلى دولة قطر في الغرب. سميت عاصمة دولة الإمارات العربية المتحدة أبو ظبي على اسم غزال صغير قاد قبيلة ضائعة إلى المياه العذبة على جزيرة لا يزيد عدد أكواخها من سعف النخيل (البراستي) عن 300 كوخ، مع عدد قليل من المباني المرجانية وحصن الحاكم. تحولت هذه الجزيرة البسيطة وتطور سكانها بمرور الوقت، وهي اليوم مدينة أبو ظبي الحديثة العالمية وعاصمة دولة الإمارات العربية المتحدة بمبانيها الشاهقة. يمزج هذا الأرخبيل الرائع بين التاريخ القديم والثقافة الغنية والتراث الغني والطبيعة الخلابة والشواطئ الجميلة والفخامة الراقية والحياة البرية المذهلة والمغامرات العائلية ومرافق التسوق ذات المستوى العالمي وملاعب الجولف الشهيرة والأجواء الفسيحة المميزة",
    descriptionEN:
      "The capital of the United Arab Emirates, located on Abu Dhabi Island, extends to the largest of the seven emirates, and includes the mainland and islands. The city of Abu Dhabi is the capital of the federal state, and it also has the largest coastline compared to the other emirates, which extends from the Emirate of Dubai in the north to the State of Qatar in the west. The capital of the United Arab Emirates, Abu Dhabi, was named after a small gazelle that led a lost tribe to fresh water on an island with no more than 300 palm frond huts (Barasti), with a few coral buildings and the ruler’s fort. This simple island has transformed and its population has developed over time, and today it is the modern, global city of Abu Dhabi and the capital of the United Arab Emirates with its high-rise buildings. This blends The wonderful archipelago .Between ancient history, rich culture, rich heritage, stunning nature, beautiful beaches, high-end luxury, amazing wildlife, family adventures, world-class shopping facilities, famous golf courses and a distinctive spacious atmosphere",
    descriptionRU:
      "Столица Объединенных Арабских Эмиратов, расположенная на острове Абу-Даби, простирается до самого большого из семи эмиратов и включает в себя материк и острова. Город Абу-Даби является столицей федерального государства, а также имеет самую большую береговую линию по сравнению с другими эмиратами, которая простирается от эмирата Дубай на севере до государства Катар на западе. Столица Объединенных Арабских Эмиратов, Абу-Даби, была названа в честь небольшой газели, которая привела заблудившееся племя к пресной воде на острове с не более чем 300 пальмовыми хижинами (Барасти), с несколькими коралловыми постройками и фортом правителя. Этот простой остров преобразился, и его население со временем разрослось, и сегодня это современный глобальный город Абу-Даби и столица Объединенных Арабских Эмиратов с его высотными зданиями. Это сочетание прекрасного архипелага . Между древней историей, богатой культурой, богатым наследием, потрясающей природой, прекрасными пляжами, элитной роскошью, удивительной дикой природой, семейными приключениями, первоклассными торговыми центрами, известными полями для гольфа и особой просторной атмосферой",
  },
  {
    nameAR: "جامع الشيخ زايد بن سلطان آل نهيان",
    url: "",
    nameEN: "Sheikh Zayed Bin Sultan Al Nahyan Mosque",
    nameRU: "Мечеть шейха Заида бин Султана Аль Нахья n",
    src: "/images/UAE/13.webp",
    descriptionAR:
      "بني مسجد الشيخ زايد بناء على توجيهات المغفور له الشيخ زايد بن سلطان آل نهيان، ويعد المسجد الذي صمم وفق معايير معمارية وجمالية أحد أهم معالم المدينة، واستخدم في بنائه أجود أنواع الرخام والحجر والذهب والأحجار الكريمة والكريستال والسيراميك. ويبلغ عدد الأعمدة داخل قاعة الصلاة الرئيسية 24 عموداً تدعم السقف والقباب الضخمة، وقد صممت بحيث ينقسم كل عمود إلى أربعة أعمدة تدعم الأقواس التي تدعم القباب، وقد كُسي هذا العمود بالرخام الأبيض المطعم بالصدف على شكل زخارف ونقوش نباتية ونباتية، مما يضفي عليه جمالاً وروعة. وفي القاعة كُسيت أرضية المسجد بأكبر سجادة في العالم، بمساحة 5627 متراً مربعاً، وصممت بفنون راقية وجميلة تضفي على المسجد طابعاً فريداً. ويبلغ عدد القباب في هذا المسجد 82 قبة بأحجام مختلفة. القبة الرئيسية للمسجد هي أكبر قبة في العالم، بارتفاع 83 متراً وقطر داخلي 32.8، وتزن القبة ألف طن، وهي مزخرفة من الداخل بالجبس المقوى بالألياف، الذي صممه فنانون عرب بزخارف نباتية فريدة، صممت خصيصاً للمسجد، بالإضافة إلى كتابة آيات من القرآن الكريم. وهو سادس أكبر مسجد في العالم من حيث المساحة الإجمالية بعد المسجد الحرام والمسجد النبوي والمسجد الأعظم في الجزائر والمسجد الأموي في دمشق ومسجد الحسن الثاني في الدار البيضاء، بمساحة 412.22 متراً مربعاً، باستثناء البحيرات العاكسة المحيطة به. وقد بني المسجد على ارتفاع 9 أمتار عن مستوى الشارع بناء على أوامر الشيخ زايد نفسه، حتى يمكن رؤية المسجد من زوايا مختلفة ومن مسافة بعيدة.",
    descriptionEN:
      "Sheikh Zayed Mosque was built on the instructions of the late Sheikh Zayed bin Sultan Al Nahyan. The mosque, which was designed according to architectural and aesthetic standards, is one of the city’s main landmarks. The finest types of marble, stone, gold, precious stones, crystal and ceramics were used in its construction. The number of columns inside the main prayer hall is 24 columns that support the ceiling and the huge domes. They were designed so that each column is divided into four pillars, which support the arches that support the domes. This column is covered with white marble inlaid with mother-of-pearl in the form of floral and plant decorations and engravings, which adds beauty and splendor. In the hall, the floor of the mosque is covered with the largest carpet in the world, with an area of ​​5,627 square meters, and designed with fine and beautiful arts that add a unique feature to the mosque. The number of domes in this mosque reaches 82 domes of different sizes. The main dome of the mosque is the largest dome in the world, with a height of 83 meters and an internal diameter of 32.8. The dome weighs a thousand tons, and is decorated from the inside with fiber-reinforced gypsum, designed by Arab artists with unique plant motifs, designed specifically for the mosque, in addition to writing verses from the Qur’an. It is the sixth largest mosque in the world in terms of total area after the Grand Mosque, the Prophet’s Mosque, the Great Mosque in Algeria, the Umayyad Mosque in Damascus, and the Hassan II Mosque in Casablanca, with an area of ​​412.22 square meters, excluding the reflective lakes around it. The mosque was built at a height of 9 meters above street level based on the orders of Sheikh Zayed himself, so that the mosque can be seen from different angles and from a long distance.",
    descriptionRU:
      "Мечеть шейха Зайда была построена по указанию покойного шейха Зайда бин Султана Аль Нахайяна. Мечеть, которая была спроектирована в соответствии с архитектурными и эстетическими стандартами, является одной из главных достопримечательностей города. При ее строительстве использовались лучшие виды мрамора, камня, золота, драгоценных камней, хрусталя и керамики. Количество колонн внутри главного молитвенного зала составляет 24 колонны, которые поддерживают потолок и огромные купола. Они были спроектированы так, что каждая колонна разделена на четыре столба, которые поддерживают арки, поддерживающие купола. Эта колонна покрыта белым мрамором, инкрустированным перламутром в виде цветочных и растительных украшений и гравюр, что добавляет красоты и великолепия. В зале пол мечети покрыт самым большим ковром в мире, площадью 5627 квадратных метров, и оформлен с использованием изящных и красивых искусств, которые добавляют мечети уникальность. Количество куполов в этой мечети достигает 82 куполов разных размеров. Главный купол мечети является самым большим куполом в мире, его высота составляет 83 метра, а внутренний диаметр — 32,8. Купол весит тысячу тонн, а изнутри он украшен армированным волокном гипсом, разработанным арабскими художниками с уникальными растительными мотивами, разработанными специально для мечети, в дополнение к написанию аятов из Корана. Это шестая по величине мечеть в мире по общей площади после Большой мечети, Мечети Пророка, Большой мечети в Алжире, Мечети Омейядов в Дамаске и Мечети Хасана II в Касабланке, ее площадь составляет 412,22 квадратных метра, без учета отражающих озер вокруг нее. Мечеть была построена на высоте 9 метров над уровнем улицы на основе приказа самого шейха Зайда, так что мечеть можно увидеть с разных сторон и с большого расстояния.",
  },
  {
    nameAR: "حصن المقطع",
    url: "",
    nameEN: "Al Maqta Fort",
    nameRU: "Форт Макта",
    src: "/images/UAE/14.webp",
    descriptionAR:
      "وتضم منطقة المقطع مباني ومنشآت تعود إلى عصر ما قبل النفط وما بعده، فضلاً عن مراحل انتقالية مختلفة عبر تاريخ دولة الإمارات العربية المتحدة. وتشكل هذه المنطقة ممراً مائياً يفصل جزيرة أبوظبي عن البر الرئيسي، وهي عبارة عن تجمع يضم العديد من المباني والمنشآت المهمة، مثل حصن المقطع وجسر المقطع وهيئة البيئة وتنمية الحياة البرية وهيئة البيئة أبوظبي وجسر الشيخ زايد. وبالتالي فهي شاهد على مراحل التطور والنمو المتعاقبة في أبوظبي. ويمثل الموقع الاستراتيجي للمنطقة البوابة الأصلية للجزيرة ونقطة الاتصال البري مع الإمارات الأخرى، لذا فهي تشكل قيمة مضافة للأهمية السياسية والرمزية للعاصمة أبوظبي. وقد تم بناؤها قبل نحو 200 عام؛ بهدف حماية الإمارة من هجمات قطاع الطرق. ونظراً لقيمتها التراثية العالية في تاريخ الإمارة، فقد خضع حصن المقطع لعمليات ترميم مهمة في السنوات الأخيرة، كما حدث مع معظم حصون الدولة.",
    descriptionEN:
      "The Al Maqta area includes buildings and structures dating back to the pre-oil era and beyond, as well as various transitional stages throughout the history of the United Arab Emirates. This area forms a waterway separating Abu Dhabi Island from the mainland, and is a cluster that embraces many important buildings and structures, such as Al Maqta Fort, Al Maqta Bridge, the Environment Research and Wildlife Development Authority, the Environment Agency Abu Dhabi, and Sheikh Zayed Bridge. Thus, it is a witness to the successful stages of development and growth in Abu Dhabi The strategic location of the area represents the original gateway to the island and the point of connection by land with other emirates, so it is an added value to the political and symbolic importance of the capital, Abu Dhabi. It was built about 200 years ago; With the aim of protecting the emirate from attacks by bandits. Due to its high heritage value in the history of the Emirates, Al Maqta Fort has undergone important restoration operations in recent years, as has been the case with most of the country’s forts.",
    descriptionRU:
      "Район Аль-Макта включает здания и сооружения, относящиеся к донефтяной эпохе и более поздним временам, а также к различным переходным этапам на протяжении всей истории Объединенных Арабских Эмиратов. Этот район образует водный путь, отделяющий остров Абу-Даби от материка, и представляет собой кластер, который охватывает множество важных зданий и сооружений, таких как Форт Аль-Макта, мост Аль-Макта, Управление по исследованию окружающей среды и развитию дикой природы, Агентство по охране окружающей среды Абу-Даби и мост шейха Заида. Таким образом, он является свидетелем последовательных этапов развития и роста в Абу-Даби. Стратегическое расположение района представляет собой изначальные ворота на остров и точку соединения по суше с другими эмиратами, поэтому он является дополнительной ценностью для политического и символического значения столицы Абу-Даби. Он был построен около 200 лет назад с целью защиты эмирата от нападений бандитов. В связи с его высокой исторической ценностью в истории эмирата, в последние годы форт Аль-Макта, как и большинство фортов страны, подвергся масштабным реставрационным работам.",
  },
  {
    nameAR: "قرية التراث",
    url: "",
    nameEN: "Culture village",
    nameRU: "Культурная деревня",
    src: "/images/UAE/15.webp",
    descriptionAR:
      "افتتح الشيخ زايد آل نهيان قرية التراث في أبوظبي عام 1996، ويشار إليها أحيانًا بقرية زايد التراثية. وتغطي القرية مساحة 16800 متر مربع، وتجسد الإرث الثقافي والحضاري لدولة الإمارات العربية المتحدة قبل اكتشاف النفط. وكانت فكرة المشروع هي تعريف العالم بالتراث العربي. وتقع قرية التراث بالقرب من وسط المدينة، وتوفر لمحة عن ماضي أبوظبي. ويمكن للسياح التسوق ومشاهدة الحرف اليدوية. كما تضم ​​القرية نادي تراث الإمارات، الذي يستضيف ورش عمل الحرف التقليدية، فضلاً عن فرصة رؤية الحرفيين وهم يصنعون الأعمال المعدنية والفخار والنسيج والغزل. وينظم هذا المهرجان الثقافي من قبل دائرة الثقافة والسياحة في أبوظبي، وهو أحد أكثر الفعاليات شعبية في العاصمة. بالإضافة إلى ذلك، توفر قرية التراث فرصة تجربة ركوب الجمال.",
    descriptionEN:
      "The Heritage Village in Abu Dhabi was opened in 1996 by Sheikh Zayed Al Nahyan, and is sometimes referred to as the Zayed Heritage Village. The village covers an area of ​​16,800 square metres, embodying the UAE’s cultural and civilizational legacy before the discovery of oil. The idea behind the project was to introduce the world to Arab heritage. Located near the city centre, the Heritage Village offers a glimpse into Abu Dhabi’s past. Tourists can shop and view handicrafts. The village is also home to the Emirates Heritage Club, which hosts traditional craft workshops, as well as the opportunity to see artisans making metalwork, pottery, weaving and spinning. Organised by the Department of Culture and Tourism in Abu Dhabi, this cultural festival is one of the most popular events in the capital. In addition, the Heritage Village offers the opportunity to experience camel riding.",
    descriptionRU:
      "Деревня наследия в Абу-Даби была открыта в 1996 году шейхом Заидом Аль Нахайяном и иногда ее называют Деревней наследия Заида. Деревня занимает площадь 16 800 квадратных метров, воплощая культурное и цивилизационное наследие ОАЭ до открытия нефти. Идея проекта заключалась в том, чтобы познакомить мир с арабским наследием. Расположенная недалеко от центра города, Деревня наследия предлагает заглянуть в прошлое Абу-Даби. Туристы могут совершать покупки и смотреть на изделия ручной работы. В деревне также находится Клуб наследия Эмиратов, где проводятся традиционные ремесленные мастерские, а также предоставляется возможность увидеть мастеров, изготавливающих изделия из металла, керамику, ткацкие и прядильные изделия. Этот культурный фестиваль, организованный Департаментом культуры и туризма Абу-Даби, является одним из самых популярных мероприятий в столице. Кроме того, Деревня наследия предлагает возможность покататься на верблюдах.",
  },
  {
    nameAR: "متحف اللوفر آبو ظبي",
    url: "",
    nameEN: "Louvre Abu Dhabi",
    nameRU: "Лувр Абу-Даби",
    src: "/images/UAE/16.webp",
    descriptionAR:
      "هو متحف فني بني في مدينة أبوظبي، صممه المهندس المعماري الفرنسي جان نوفيل، وافتتح في 8 نوفمبر 2017 وفتح أبوابه أمام الزوار في 11 نوفمبر 2017. المتحف الذي كان من المقرر أن يبنى بموجب اتفاقية موقعة بين مدينة أبوظبي والحكومة الفرنسية، أنشئ لمدة ثلاثين عامًا على مساحة تقارب 24 ألف متر مربع في جزيرة السعديات، بتكلفة تقدر بين 83 و108 ملايين يورو. وبحسب مسؤولي المشروع، سيكون هذا المتحف معرضًا للتحف الفنية من جميع أنحاء العالم، والهدف الرئيسي للمشروع هو أن يكون حلقة وصل بين الفن الشرقي والغربي. وقد أثارت مسألة كيفية استفادة متحف اللوفر في باريس منه جدلاً حادًا في عالم الفن. 󀟽 من هذه الاتفاقية تعد جزيرة السعديات أكبر مجمع ثقافي في العالم تحت سقف واحد، حيث صممت شركة فوستر آند بارتنرز متحف زايد الوطني بالإضافة إلى متحف اللوفر أبوظبي. وتمتد مساحة الموقع على مساحة 97 ألف متر مربع في جزيرة السعديات، وقد صمم المتحف على شكل مدينة مصغرة تشبه أرخبيلاً في البحر، ويضم 55 مبنى أبيض اللون مستوحى من تصاميم المنازل المنخفضة الارتفاع في العمارة العربية التقليدية، ويضم المتحف 23 قاعة عرض دائمة تعرض روائع فنية تحكي قصصاً من العصور التاريخية المختلفة التي مرت بها البشرية حتى الوقت الحاضر في 12 سلسلة مختلفة، وتغطي القبة التي يبلغ قطرها 180 متراً معظم أجزاء الجزيرة ومدينة أبوظبي بشكل عام.",
    descriptionEN:
      "It is an art museum built in the city of Abu Dhabi, designed by the French architect Jean Nouvel. It was opened on November 8, 2017 and opened its doors to visitors on November 11, 2017. The museum, which was intended to be built under an agreement signed between the city of Abu Dhabi and the French government, was established for a period of thirty years on an area of ​​approximately 24,000 square meters on Saadiyat Island, at a cost estimated between 83 and 108 million euros. According to project officials, this museum will be an exhibition of artistic artifacts from all over the world, and the main goal of the project is to be a link between Eastern and Western art. The issue of how the Louvre Museum in Paris will benefit from it has caused heated debate in the art world. 􀟽 From this agreement Saadiyat Island is the largest cultural complex in the world under one roof. Foster + Partners designed the Zayed National Museum in addition to the Louvre Abu Dhabi Museum. The site area extends over 97 thousand square meters on Saadiyat Island. The museum is designed in the form of a miniature city resembling an archipelago in the sea and includes 􀟽 55 white buildings inspired by the designs of low-rise houses in traditional Arab architecture. The museum includes 23 permanent exhibition halls that display artistic masterpieces that tell stories from the different historical eras that humanity has gone through to the present time in 12 different series. The dome, with a diameter of 180 meters, covers most parts of the island and the city of Abu Dhabi in general.",
    descriptionRU:
      "Это художественный музей, построенный в городе Абу-Даби по проекту французского архитектора Жана Нувеля. Он был открыт 8 ноября 2017 года и открыл свои двери для посетителей 11 ноября 2017 года. Музей, который должен был быть построен в соответствии с соглашением, подписанным между городом Абу-Даби и французским правительством, был создан сроком на тридцать лет на площади около 24 000 квадратных метров на острове Саадият, стоимость которого оценивается от 83 до 108 миллионов евро. По словам должностных лиц проекта, этот музей будет выставкой художественных артефактов со всего мира, а главная цель проекта — стать связующим звеном между восточным и западным искусством. Вопрос о том, как от этого выиграет музей Лувр в Париже, вызвал бурные дебаты в мире искусства. ܀�� Из этого соглашения Остров Саадият является крупнейшим культурным комплексом в мире под одной крышей. Foster + Partners спроектировали Национальный музей Зайеда в дополнение к музею Лувр Абу-Даби. Площадь участка простирается на 97 тысяч квадратных метров на острове Саадият. Музей спроектирован в виде миниатюрного города, напоминающего архипелаг в море, и включает ܀�� 55 белых зданий, вдохновленных проектами малоэтажных домов в традиционной арабской архитектуре. Музей включает 23 постоянных выставочных зала, в которых представлены художественные шедевры, рассказывающие истории из разных исторических эпох, которые пережило человечество до настоящего времени в 12 различных сериях. Купол диаметром 180 метров покрывает большую часть острова и города Абу-Даби в целом.",
  },
  {
    nameAR: "عالم فيراري",
    url: "",
    nameEN: "Ferrari world",
    nameRU: "Мир Феррари",
    src: "/images/UAE/17.webp",
    descriptionAR:
      "عالم فيراري أبوظبي هو أول منتزه ترفيهي في العالم مستوحى من فيراري، ويقع على جزيرة ياس في أبوظبي، ويضم فورمولا روسا، أسرع أفعوانية في العالم. وُضع حجر الأساس للمنتزه في 3 نوفمبر 2007. واستغرق تطوير المنتزه ثلاث سنوات وافتتح رسميًا للجمهور في 4 نوفمبر 2010. إنه عالم كامل مصمم لإشباع شغفك بالسرعة مع اندفاع الأدرينالين في كل جانب. اشعر بالشغف والطاقة التي تسرع النبض في قلب أبوظبي. يضم عالم فيراري أبوظبي أكثر من 40 لعبة تحطم الأرقام القياسية ومرافق ترفيهية مثيرة.",
    descriptionEN:
      "An indoor theme park located on Yas Island in Abu Dhabi, Ferrari World Abu Dhabi is the world’s first Ferrari-themed park featuring Formula Rossa, the world’s fastest roller coaster. The park’s foundation stone was laid on November 3, 2007. The park took three years to develop and was officially opened to the public on November 4, 2010. It is a complete world designed to satisfy your passion for speed with an adrenaline rush in every aspect. Feel the passion and energy that accelerates the pulse in the heart of Abu Dhabi. Ferrari World Abu Dhabi features more than 40 record-breaking rides and exciting entertainment facilities.",
    descriptionRU:
      "Крытый тематический парк, расположенный на острове Яс в Абу-Даби, Ferrari World Abu Dhabi — первый в мире тематический парк Ferrari с Formula Rossa, самыми быстрыми в мире американскими горками. Первый камень в фундамент парка был заложен 3 ноября 2007 года. На разработку парка ушло три года, и он был официально открыт для публики 4 ноября 2010 года. Это целый мир, созданный для удовлетворения вашей страсти к скорости с выбросом адреналина в каждом аспекте. Почувствуйте страсть и энергию, которые ускоряют пульс в самом сердце Абу-Даби. Ferrari World Abu Dhabi предлагает более 40 рекордных аттракционов и захватывающие развлекательные объекты.",
  },
  {
    nameAR: "قصر الوطن",
    url: "",
    nameEN: "Palace of the homeland",
    nameRU: "Дворец Аль-Ватан",
    src: "/images/UAE/18.webp",
    descriptionAR:
      "صرح معماري فريد يجسد مسيرة التقدم في دولة الإمارات العربية المتحدة، ويشكل جسراً للتواصل الفكري والثقافي بين شعوب العالم. يتيح لك القصر بأروقته الفخمة فرصة تعزيز وإثراء تجاربك المعرفية، بالإضافة إلى تسليط الضوء على تراثنا العربي الغني الذي يعكس هويتنا وإرثنا الفريد. يعد القصر تحفة فنية معمارية رائعة، حيث يمكنك التجول بين أروقة القصر المستوحاة من التقاليد العربية الأصيلة، ونوافذه التي تجسد روح الأمة المتطلعة إلى المستقبل.",
    descriptionEN:
      "A unique architectural monument that embodies the march of progress in the United Arab Emirates, and forms a bridge for intellectual and cultural communication between the peoples of the world. The palace, with its luxurious corridors, allows you the opportunity to enhance and enrich your cognitive experiences, in addition to shedding light on our rich Arab heritage that reflects our identity and our unique legacy. The palace is a wonderful masterpiece of architectural art, where you can wander between the palace corridors inspired by authentic Arab traditions, and its windows that embody the spirit of the nation looking forward.",
    descriptionRU:
      "Уникальный архитектурный памятник, олицетворяющий марш прогресса в Объединенных Арабских Эмиратах и ​​образующий мост для интеллектуального и культурного общения между народами мира. Дворец с его роскошными коридорами дает вам возможность расширить и обогатить ваши познавательные впечатления, а также пролить свет на наше богатое арабское наследие, отражающее нашу идентичность и наше уникальное наследие. Дворец является прекрасным шедевром архитектурного искусства, где вы можете бродить между дворцовыми коридорами, вдохновленными подлинными арабскими традициями, и его окнами, которые олицетворяют дух нации, устремленной в будущее.",
  },
  {
    nameAR: "بابس هندو ماندير",
    url: "",
    nameEN: "BAPS Hindu Mandir",
    nameRU: "БАПС Индуистский Мандир",
    src: "/images/UAE/19.webp",
    descriptionAR:
      "يقع المشروع في أبوظبي، وهو مشروع ثقافي وديني مهم، ويمثل بناء أول معبد حجري هندوسي تقليدي في الشرق الأوسط. بدأ المشروع بعد أن قررت حكومة الإمارات تخصيص أرض للمعبد خلال زيارة رئيس الوزراء الهندي ناريندرا مودي في عام 2015. وقد تم منح الأرض للمعبد من قبل ولي عهد أبوظبي الشيخ محمد بن زايد آل نهيان. تم وضع حجر الأساس في عام 2018. المعبد مصنوع من الحجر الرملي الوردي من ولاية راجستان في الهند، والمعروف بمتانته في درجات الحرارة القصوى. يتماشى هذا الاختيار من المواد مع الهندسة المعمارية التقليدية للمعابد الهندوسية، والتي تتجنب استخدام الفولاذ أو الحديد. ومن المتوقع أن يكون المعبد مماثلاً في الحجم لمعبد أكشاردام في نيوجيرسي، وسيضم منحوتات رخامية على خلفية من الحجر الرملي. سيضم معبد BAPS Hindu Mandir سبعة أضرحة مخصصة لآلهة هندوسية مختلفة، مما يعكس احترام دولة الإمارات العربية المتحدة للمجتمع. كما سيضم مدرجًا وقاعة معارض ومكتبة وقاعات دراسية ومركزًا رياضيًا وقاعة طعام ومركزين مجتمعيين بسعة 5000 شخص. ويمتد مجمع المعبد على مساحة 55 ألف متر مربع، مما يوفر واحة روحية من الانسجام العالمي.",
    descriptionEN:
      "Located in Abu Dhabi, the project is a significant cultural and religious project, and represents the construction of the first traditional Hindu stone temple in the Middle East. The project began after the UAE government decided to allocate land for the temple during a visit by Indian Prime Minister Narendra Modi in 2015. The land was gifted to the temple by the Crown Prince of Abu Dhabi, Sheikh Mohammed bin Zayed Al Nahyan. The foundation stone was laid in 2018. The temple is made of pink sandstone from the state of Rajasthan in India, known for its durability in extreme temperatures. This choice of materials is in keeping with traditional Hindu temple architecture, which avoids the use of steel or iron. The temple is expected to be similar in scale to the Akshardham Temple in New Jersey, and will feature marble sculptures against a sandstone background. The BAPS Hindu Mandir will feature seven shrines dedicated to various Hindu deities, reflecting the UAE’s respect for the community. It will also feature an amphitheatre, exhibition hall, library, classrooms, a sports centre, a dining hall and two community centres with a capacity of 5,000 people. The temple complex spans an area of ​​55,000 square metres, providing a spiritual oasis of global harmony.",
    descriptionRU:
      "Расположенный в Абу-Даби, проект является значимым культурным и религиозным проектом и представляет собой строительство первого традиционного индуистского каменного храма на Ближнем Востоке. Проект начался после того, как правительство ОАЭ приняло решение выделить землю для храма во время визита премьер-министра Индии Нарендры Моди в 2015 году. Земля была подарена храму наследным принцем Абу-Даби шейхом Мухаммедом бин Заидом Аль Нахайяном. Первый камень в фундамент был заложен в 2018 году. Храм построен из розового песчаника из штата Раджастхан в Индии, известного своей прочностью при экстремальных температурах. Такой выбор материалов соответствует традиционной архитектуре индуистских храмов, которая избегает использования стали или железа. Ожидается, что храм будет аналогичен по масштабу храму Акшардхам в Нью-Джерси и будет включать мраморные скульптуры на фоне песчаника. В индуистском мандире BAPS будет семь святилищ, посвященных различным индуистским божествам, что отражает уважение ОАЭ к сообществу. Также в нем будут амфитеатр, выставочный зал, библиотека, классы, спортивный центр, столовая и два общественных центра вместимостью 5000 человек. Храмовый комплекс занимает площадь 55 000 квадратных метров, представляя собой духовный оазис глобальной гармонии.",
  },
  {
    nameAR: "فنادق في آبو ظبي",
    url: "",
    nameEN: "Hotels in Abu Dhabi",
    nameRU: "Отели в Абу-Даби",
  },
  {
    nameAR: "Emirates Palace Mandarin Oriental",
    url: "",
    nameEN: "Emirates Palace Mandarin Oriental",
    nameRU: "Emirates Palace Mandarin Oriental",
    src: "/images/UAE/20.webp",
    descriptionAR:
      "فندق فخم عالمي المستوى يقع في قلب عاصمة الإمارات العربية المتحدة أبوظبي. ورغم أن فندق قصر الإمارات أبوظبي من فئة 5 نجوم، إلا أنه يعد من أهم المعالم السياحية في أبوظبي، حيث يقصده السكان من مختلف أنحاء الدولة والعالم لاستكشاف تصاميمه وهندسته المعمارية. افتتح فندق قصر الإمارات في عام 2005، أما مطاعم ومنتجعات الفندق فقد افتتحت في عام 2006. صمم فندق قصر الإمارات أبوظبي المهندس المعماري جون إي إليوت. يضم المبنى الرئيسي لفندق قصر الإمارات أبوظبي 114 قبة رخامية، كما يضم المبنى الرئيسي شرفة كبيرة وقبة محفورة ترتفع 72.6 متراً عن الأرض ومزخرفة بشكل متقن بالذهب واللؤلؤ والكريستال. ويضم الفندق 1002 ثريا موزعة في أنحاء فندق قصر الإمارات، أكبرها وزناً 2.5 طن، بالإضافة إلى سجادتين حائطيتين يدويتي الصنع تحملان صورة الفندق. يطل على الخليج العربي ويقع بالقرب من كورنيش أبوظبي ومارينا مول وقرية التراث، كما يبعد مسافة 30 دقيقة بالسيارة عن مطار أبوظبي الدولي وساعة عن مطار آل مكتوم الدولي وساعة ونصف عن مطار دبي الدولي.",
    descriptionEN:
      "The world-class luxury hotel located in the heart of the capital of the UAE, Abu Dhabi. Although the Emirates Palace Abu Dhabi is a 5-star hotel, it is one of the most important tourist attractions in Abu Dhabi, which is visited by residents from all over the country and the world to explore its designs and architecture. The Emirates Palace Hotel was opened in 2005, and as for the hotel's restaurants and resorts, they were opened in 2006. The Emirates Palace Hotel Abu Dhabi was designed by architect John E. Elliott. The main building of the Emirates Palace Hotel Abu Dhabi includes 114 marble domes. The main building also includes a large balcony and an engraved dome rising 72.6 meters above the ground and decorated in an elaborate manner with gold, pearls and crystal. The hotel has 1002 chandeliers distributed throughout the Emirates Palace Hotel, the largest of which weighs 2.5 tons, in addition to two hand-made wall carpets bearing the image of the hotel. It overlooks the Arabian Gulf and is close to Abu Dhabi Corniche, Marina Mall and Heritage Village. It is also a 30-minute drive from Abu Dhabi International Airport, an hour from Al Maktoum International Airport and an hour and a half from Dubai International Airport.",
    descriptionRU:
      "Роскошный отель мирового класса, расположенный в самом сердце столицы ОАЭ, Абу-Даби. Хотя Emirates Palace Abu Dhabi — это 5-звездочный отель, он является одной из важнейших туристических достопримечательностей Абу-Даби, которую посещают жители со всей страны и мира, чтобы изучить ее дизайн и архитектуру. Emirates Palace Hotel был открыт в 2005 году, а что касается ресторанов и курортов отеля, то они были открыты в 2006 году. Emirates Palace Hotel Abu Dhabi был спроектирован архитектором Джоном Э. Эллиоттом. Главное здание Emirates Palace Hotel Abu Dhabi включает 114 мраморных куполов. Главное здание также включает большой балкон и гравированный купол, возвышающийся на 72,6 метра над землей и украшенный искусно золотом, жемчугом и хрусталем. В отеле есть 1002 люстры, распределенные по всему Emirates Palace Hotel, самая большая из которых весит 2,5 тонны, в дополнение к двум настенным коврам ручной работы с изображением отеля. Он выходит на Персидский залив и находится недалеко от Abu Dhabi Corniche, Marina Mall и Heritage Village. Он также находится в 30 минутах езды от международного аэропорта Абу-Даби, в часе езды от международного аэропорта Аль-Мактум и в полутора часах езды от международного аэропорта Дубая.",
  },
  {
    nameAR: "Rixos Marina Abu Dhabi",
    url: "",
    nameEN: "Rixos Marina Abu Dhabi",
    nameRU: "Rixos Marina Abu Dhabi",
    src: "/images/UAE/21.webp",
    descriptionAR:
      "يقع ريكسوس مارينا أبوظبي في أبوظبي على بعد 2.8 كم من نادي نيشن ريفييرا بيتش، ويوفر أماكن إقامة مع حديقة ومسبح خارجي وتراس. كما يتميز هذا الفندق المصنف 5 نجوم بماكينة صراف آلي ومركز أعمال. يقع الفندق على بعد 2.9 كم من شاطئ الكورنيش وعلى بعد 7.4 كم من قصر الحصن. يُعد الفندق معلمًا معماريًا بارزًا يجمع بين أفضل ما في الثقافة العربية والتركية والمطاعم والضيافة. يقع ريكسوس مارينا أبوظبي في قلب مركز التجزئة والترفيه والسكن في أبوظبي، وهو منتجع متعدد الأوجه يطل على المياه المتلألئة والساحل الرملي. يعكس ريكسوس مارينا تنوع أبوظبي كمدينة عالمية مليئة بالتجارب وأرخبيل يتمتع بتراث طبيعي بحري غني. يمزج ريكسوس مارينا أبوظبي بسلاسة بين التصميم المائي والرابسودي المتطور ليحكي قصة أبوظبي من أصولها البحرية القديمة إلى مدينة عالمية مزدهرة تفتخر بتراثها وتجاربها الفاخرة.",
    descriptionEN:
      "Located in Abu Dhabi, 2.8 km from Nation Riviera Beach Club,It offers accommodation with a garden, an outdoor pool and a terrace. This 5-star hotel also features an ATM and a business centre. The hotel is 2.9 km from Corniche Beach and 7.4 km from Qasr Al Hosn. The hotel is an iconic architectural landmark that combines the best of Arabic and Turkish culture, dining and hospitality. Located in the heart of Abu Dhabi’s retail, leisure and residential hub, Rixos Marina Abu Dhabi is a multi-faceted resort overlooking the sparkling waters and sandy coastline. Rixos Marina reflects Abu Dhabi’s diversity as a cosmopolitan city brimming with experiences and an archipelago with a rich marine natural heritage. Rixos Marina Abu Dhabi seamlessly blends aquatic design with sophisticated rhapsody to tell the story of Abu Dhabi from its ancient maritime origins to a thriving cosmopolitan city proud of its heritage and luxurious experiences.",
    descriptionRU:
      "Расположенный в Абу-Даби, в 2,8 км от Nation Riviera Beach Club, он предлагает размещение с садом, открытым бассейном и террасой. Этот 5-звездочный отель также располагает банкоматом и бизнес-центром. Отель находится в 2,9 км от пляжа Корниш и в 7,4 км от Qasr Al Hosn. Отель является знаковой архитектурной достопримечательностью, которая сочетает в себе лучшее из арабской и турецкой культуры, ресторанов и гостеприимства. Расположенный в самом сердце торгового, развлекательного и жилого центра Абу-Даби, Rixos Marina Abu Dhabi является многогранным курортом с видом на сверкающие воды и песчаное побережье. Rixos Marina отражает разнообразие Абу-Даби как космополитического города, полного впечатлений и архипелага с богатым морским природным наследием. Rixos Marina Abu Dhabi органично сочетает в себе водный дизайн и изысканную рапсодию, рассказывая историю Абу-Даби от его древних морских истоков до процветающего космополитичного города, гордящегося своим наследием и роскошными впечатлениями.",
  },
  {
    nameAR: "دبي",
    url: "",
    nameEN: "Dubai",
    nameRU: "Дубай",
    src: "/images/UAE/2.webp",
    descriptionAR:
      "هي المدينة الأكثر كثافة سكانية في دولة الإمارات العربية المتحدة، وتقع على الساحل الجنوبي الشرقي للخليج العربي، وتقع مدينة دبي على الساحل الشمالي للإمارة، وقد سُكنت دبي منذ عام 1580م، أو 900هـ، حيث ذكرها البرتغالي جاسبر بارو بالب ضمن المدن الساحلية بلفظ ديبي أي دبي، وهذا يعني أن الإمارة كانت موجودة منذ زمن بعيد قبل تهجير عام 1833م، مما يعني أن الانتقال كان إلى منطقة مأهولة بالسكان ورائدة في العمل والتجارة، ويمكن القول أن تأسيس دبي يعود إلى ثلاثينيات القرن التاسع عشر، وتحديداً عام 1833م، حيث استوطن في منطقة الخور نحو 800 شخص ينتمون إلى قبيلة بني ياس بقيادة آل مكتوم، وكان الخور في ذلك الوقت ميناءً طبيعياً للمنطقة، مما أدى لاحقاً إلى ظهور دبي كمركز لصيد الأسماك واللؤلؤ والتجارة.",
    descriptionEN:
      "It is the most densely populated city in the United Arab Emirates. It is located on the southeastern coast of the Arabian Gulf, and the city of Dubai is located on the northern coast of the emirate. Dubai has been inhabited since the year 1580 AD, or 900 AH, when the Portuguese Jasper Baro Balb mentioned it among the coastal cities with the pronunciation Dibei, meaning Dubai. This means that the emirate existed long ago before the displacement of 1833, which means that the move was to an area inhabited by residents and pioneering in work and trade. It can be said that the founding of Dubai dates back to the thirties of the nineteenth century, specifically in 1833 AD, when about 800 people belonging to the Bani Yas tribe, led by Al Maktoum, settled in the creek area. At that time, the creek was a natural port for the region, which later led to the emergence of Dubai as a center for fishing, pearling and trade.",
    descriptionRU:
      "Это самый густонаселенный город в Объединенных Арабских Эмиратах. Он расположен на юго-восточном побережье Персидского залива, а город Дубай расположен на северном побережье эмирата. Дубай был заселен с 1580 года нашей эры или 900 года по хиджре, когда португалец Джаспер Баро Балб упомянул его среди прибрежных городов с произношением Dibei, что означает Дубай. Это означает, что эмират существовал задолго до перемещения 1833 года, что означает, что перемещение было в район, населенный жителями и пионерами в работе и торговле. Можно сказать, что основание Дубая восходит к тридцатым годам девятнадцатого века, а именно к 1833 году нашей эры, когда около 800 человек, принадлежащих к племени Бани Яс, во главе с Аль Мактумом, поселились в районе ручья. В то время залив был естественным портом для региона, что впоследствии привело к становлению Дубая как центра рыболовства, добычи жемчуга и торговли.",
  },
  {
    nameAR: "برج خليفة",
    url: "",
    nameEN: "Burj Khalifa",
    nameRU: "Бурдж-Халифа",
    src: "/images/UAE/3.webp",
    descriptionAR:
      "وهو أطول مبنى في العالم حالياً، وافتتح رسمياً في عام 2010. ويتجاوز ارتفاعه 800 متر. وتبلغ المساحة الإجمالية للبرج نحو 4 ملايين متر مربع. وبدأ تشييده في 6 يناير 2004، واكتمل بناؤه الخارجي بعد خمس سنوات (في 1 أكتوبر 2009). وافتتح في 4 يناير 2010 ضمن مشروع جديد أطلق عليه اسم تطوير وسط مدينة دبي. وجاء قرار تشييد المبنى استناداً إلى رؤية الحكومة لتنويع الاقتصاد بعيداً عن النفط وجعل دبي وجهة سياحية عالمية. وكان اسم المبنى في الأصل برج دبي ولكن أعيدت تسميته تكريماً لحاكم أبوظبي ورئيس دولة الإمارات العربية المتحدة الشيخ خليفة بن زايد آل نهيان. ويتكون من 160 طابقاً ويضم أيضاً فندقاً يتألف من 403 جناحاً فندقياً. ويحتوي على 57 مصعداً كهربائياً، يصل أسرعها إلى سرعة 10 أمتار في الثانية تقريباً، ويستغرق 55 ثانية للوصول إلى ارتفاع 500 متر. البرج مملوك لشركة إعمار العقارية، إحدى أكبر شركات العقارات في العالم، وقد تولت شركة سامسونج سي آند تي كوربوريشن عملية البناء.",
    descriptionEN:
      "It is currently the tallest building in the world, and was officially opened in 2010. Its height exceeds 800 meters. The total area of ​​the tower is about 4,000,000 square meters. Construction began on 6 January 2004, and its exterior was completed five years later (on 1 October 2009). It was opened on 4 January 2010 as part of a new project called the Downtown Dubai development. The decision to build the building was based on the government's vision to diversify the economy away from oil and to make Dubai a global tourist destination. The building was originally named Burj Dubai but was renamed in honor of the ruler of Abu Dhabi and President of the United Arab Emirates, Sheikh Khalifa bin Zayed Al Nahyan. It has 160 floors and also includes a hotel consisting of 403 hotel suites. It has 57 electric elevators, the fastest of which reaches a speed of approximately 10 m/s, and it takes 55 seconds to reach a height of 500 m. The tower is owned by Emaar Properties, one of the largest Real estate companies in the world, The construction process was undertaken by Samsung C&T Corporation",
    descriptionRU:
      "В настоящее время это самое высокое здание в мире, официально открытое в 2010 году. Его высота превышает 800 метров. Общая площадь башни составляет около 4 000 000 квадратных метров. Строительство началось 6 января 2004 года, а его внешняя часть была завершена пять лет спустя (1 октября 2009 года). Оно было открыто 4 января 2010 года в рамках нового проекта под названием Downtown Dubai development. Решение о строительстве здания было основано на видении правительства диверсифицировать экономику от нефти и сделать Дубай мировым туристическим направлением. Первоначально здание называлось Burj Dubai, но было переименовано в честь правителя Абу-Даби и президента Объединенных Арабских Эмиратов шейха Халифы бин Заида Аль Нахайяна. Оно имеет 160 этажей и также включает в себя отель, состоящий из 403 гостиничных номеров. В здании 57 электрических лифтов, самый быстрый из которых развивает скорость около 10 м/с, а для достижения высоты 500 м требуется 55 секунд. Башня принадлежит Emaar Properties, одной из крупнейших компаний в сфере недвижимости в мире, а строительством занималась корпорация Samsung C&T.",
  },
  {
    nameAR: "فندق برج العر ب",
    url: "",
    nameEN: "Burj Al Arab Hotel",
    nameRU: "Отель Бурдж Аль Араб",
    src: "/images/UAE/4.webp",
    descriptionAR:
      "الفندق الوحيد في العالم المصنف كفندق 7 نجوم، افتتح رسمياً عام 1999 بتكلفة تقارب 650 مليون دولار. تم بناء البرج على جزيرة اصطناعية تبعد 100 متر عن الشاطئ. وهو من أفخم وأرقى الفنادق في العالم وتديره مجموعة فنادق جميرا. تم بناء الفندق على ارتفاع أقل بـ 60 متراً فقط من مبنى إمباير ستيت في مدينة نيويورك في الولايات المتحدة الأمريكية، لينافس بارتفاعه الشاهق على لقب أطول مبنى في العالم. يرتبط الفندق بالبر الرئيسي عبر جسر خان كيرف. افتتح الشيخ محمد بن راشد آل مكتوم حاكم دبي الفندق في 1 ديسمبر 1999. ولسنوات طويلة تصدر الفندق قائمة أطول الفنادق في العالم. ويحتل اليوم المرتبة 76 كأطول مبنى في العالم بارتفاع 321 متراً فوق مستوى سطح البحر. يعد الفندق أحد أهم المعالم السياحية في دبي ويوصف بأنه الأكثر فخامة في العالم، وهو المقر الرئيسي للملوك والرؤساء ومشاهير العالم الذين يزورون الإمارات، ويصنف كفندق سبع نجوم لفخامته.",
    descriptionEN:
      "The only hotel in the world classified as a 7-star hotel, it was officially opened in 1999 at a cost of approximately 650 million dollars. The tower is built on an artificial island 100 meters from the beach. It is one of the most luxurious and upscale hotels in the world and is managed by the Jumeirah Hotel Group. The hotel was built at a height that is only 60 meters lower than the Empire State Building in New York City in the United States of America, competing with its towering height for the tallest structure in the world. The hotel is connected to the mainland via the Khan Curve Bridge. Sheikh Mohammed bin Rashid Al Maktoum, the ruler of Dubai, opened the hotel on December 1, 1999. For years, the hotel topped the list of the tallest hotels in the world. Today, it ranks 76th as the tallest building in the world at a height of 321 meters above sea level. The hotel is one of Dubai's most important tourist attractions and is described as The most luxurious in the world, it is the main headquarters for kings, presidents and world celebrities who visit the Emirates, and it is classified as a seven-star hotel for its luxury.",
    descriptionRU:
      "Единственный отель в мире, классифицированный как 7-звездочный, он был официально открыт в 1999 году и стоил около 650 миллионов долларов. Башня построена на искусственном острове в 100 метрах от пляжа. Это один из самых роскошных и высококлассных отелей в мире, которым управляет Jumeirah Hotel Group. Отель был построен на высоте, которая всего на 60 метров ниже, чем Empire State Building в Нью-Йорке в Соединенных Штатах Америки, конкурируя своей возвышающейся высотой за самое высокое сооружение в мире. Отель соединен с материком через мост Khan Curve Bridge. Шейх Мохаммед бин Рашид Аль Мактум, правитель Дубая, открыл отель 1 декабря 1999 года. В течение многих лет отель возглавлял список самых высоких отелей в мире. Сегодня он занимает 76-е место как самое высокое здание в мире с высотой 321 метр над уровнем моря. Отель является одной из важнейших туристических достопримечательностей Дубая и считается самым роскошным в мире. Это главная резиденция королей, президентов и мировых знаменитостей, посещающих Эмираты. За свою роскошь он классифицируется как семизвездочный отель.",
  },
  {
    nameAR: "نخلة جميرا",
    url: "",
    nameEN: "Palm Jumeirah",
    nameRU: "Пальма Джумейра",
    src: "/images/UAE/5.webp",
    descriptionAR:
      "وهي أصغر مجموعة من ثلاث جزر صناعية على شكل أشجار النخيل تعرف باسم'جزر النخيل' في دبي بالإمارات العربية المتحدة، وهي مصممة على شكل شجرة نخيل مكونة من ثلاثة أجزاء: الجذع والتاج وسعفها، وتحيط بها حاجز نصف دائري يشكل شعاباً بحرية صناعية، والسعف كلها مناطق سكنية وفلل، بينما تشهد منطقة الحاجز البحري بناء 7 فنادق ضخمة ومنتجعات عملاقة، منها منتجع أتلانتس الذي يوحي اسمه بجزيرة أتلانتس الأسطورية، ويضم الفندق 1539 غرفة، ما يجعله أكبر فندق في الشرق الأوسط، كما تشهد الجزيرة بناء ناطحة سحاب برج ترامب الذي سيصبح معلماً من معالم دبي.",
    descriptionEN:
      "It is the smallest of a group of three artificial islands in the shape of palm trees known as the 'Palm Islands' in Dubai, UAE. It is designed in the shape of a palm tree consisting of three parts: the trunk, the crown and its fronds. It is surrounded by a semi-circular barrier forming an artificial sea reef. The fronds are all residential areas and villas, while the sea barrier area is witnessing 7 huge hotels and giant resorts, including the Atlantis Resort, whose name suggests the legendary island of Atlantis. The hotel includes 1,539 rooms, making it the largest hotel in the Middle East. The island is also witnessing the construction of the Trump Tower skyscraper, which will become a landmark of Dubai.",
    descriptionRU:
      "Это самый маленький из группы из трех искусственных островов в форме пальм, известных как «Пальмовые острова» в Дубае, ОАЭ. Он спроектирован в форме пальмы, состоящей из трех частей: ствола, кроны и ее листьев. Он окружен полукруглым барьером, образующим искусственный морской риф. Листья представляют собой жилые районы и виллы, в то время как в зоне морского барьера расположены 7 огромных отелей и гигантских курортов, включая Atlantis Resort, чье название намекает на легендарный остров Атлантида. Отель включает в себя 1539 номеров, что делает его крупнейшим отелем на Ближнем Востоке. На острове также ведется строительство небоскреба Trump Tower, который станет достопримечательностью Дубая.",
  },
  {
    nameAR: "سكي دبي",
    url: "",
    nameEN: "Ski Dubai",
    nameRU: "Лыжный Дубай",
    src: "/images/UAE/6.webp",
    descriptionAR:
      "يقع منتجع سكي دبي، أول منتجع تزلج داخلي في الشرق الأوسط، في مول الإمارات، ويمتد على مساحة ضخمة تبلغ 22500 متر مربع من الثلوج، تغطي 5 منحدرات تزلج بدرجات انحدار متفاوتة، بالإضافة إلى منطقة حرة لمتزلجي الثلوج والألواح الثلجية. وبجانب منحدرات التزلج، تقع حديقة الثلوج التي تمتد على مساحة 3000 متر مربع، وتحتوي على مجموعة واسعة من الأنشطة للأشخاص الذين لا يستطيعون التزلج أو لا يرغبون فيه. كما أنها رائعة للعائلات، حيث تضم كهوفًا ثلجية ومنحدرات انزلاقية ورحلات أنابيب. بالإضافة إلى مقهى الجبل، حيث يمكنك تناول مشروب ساخن في مكان تصل فيه درجة الحرارة إلى أربع درجات تحت الصفر، أو مشاهدة مستعمرة البطاريق في نزهتها اليومية والتقاط الصور معها، والتي تحظى بشعبية كبيرة لدى الأشخاص من جميع الأعمار.",
    descriptionEN:
      "The first indoor ski resort in the Middle East, Ski Dubai is located in the Mall of the Emirates. It has a huge area of ​​22,500 square metres of snow, covering 5 ski slopes of varying degrees of incline, in addition to a free zone for snowboarders and snowboarders. Next to the ski slopes is the Snow Park, which extends over an area of ​​3,000 square metres. It contains a wide range of activities for people who cannot or do not want to ski. It is also great for families, as it features snow caves, sliding slopes and tubing trips. In addition to the mountain café, where you can have a hot drink in a place where the temperature reaches four degrees below zero, or watch the colony of penguins on their daily walk and take pictures with them, which is very popular with people of all ages.",
    descriptionRU:
      "Первый крытый горнолыжный курорт на Ближнем Востоке, Ski Dubai, расположен в торговом центре Mall of the Emirates. Он имеет огромную площадь в 22 500 квадратных метров снега, покрывающего 5 горнолыжных трасс разной степени наклона, в дополнение к бесплатной зоне для сноубордистов и сноубордистов. Рядом с горнолыжными трассами находится Snow Park, который простирается на площади 3 000 квадратных метров. Он содержит широкий спектр мероприятий для людей, которые не могут или не хотят кататься на лыжах. Он также отлично подходит для семей, так как здесь есть снежные пещеры, скользящие склоны и поездки на тюбингах. В дополнение к горному кафе, где можно выпить горячий напиток в месте, где температура достигает четырех градусов ниже нуля, или понаблюдать за колонией пингвинов во время их ежедневной прогулки и сфотографироваться с ними, что очень популярно среди людей всех возрастов.",
  },
  {
    nameAR: "متحف المستقبل",
    url: "",
    nameEN: "Museum of the Future",
    nameRU: "Музей будущего",
    src: "/images/UAE/7.webp",
    descriptionAR:
      "هو عبارة عن مساحة عرض للأيديولوجيات والخدمات والمنتجات المبتكرة والمستقبلية، يقع متحف المستقبل في الحي المالي بدبي، ويضم ثلاثة عناصر رئيسية هي التل الأخضر والمبنى والفراغ، أسست مؤسسة دبي للمستقبل، حكومة دولة الإمارات العربية المتحدة، المتحف وافتتحته في 22 فبراير 2022، وتم اختيار التاريخ رسميًا لأن 22 فبراير 2022 هو تاريخ الباليندرم، ويهدف هذا المتحف إلى تعزيز التطور التكنولوجي والابتكار، وخاصة في مجالات الروبوتات الاصطناعية، ويقع المتحف في منطقة أبراج الإمارات بالقرب من شارع الشيخ زايد في دبي، ويمتد المتحف على مساحة 30 ألف متر مربع ويبلغ ارتفاعه 77 مترًا، ويتكون من سبعة طوابق بينما يتم تغذيته بـ 4000 ميجاوات من الكهرباء المنتجة من خلال الطاقة الشمسية، عبر محطة خاصة متصلة بالمتحف تم بناؤها بالتعاون مع هيئة كهرباء ومياه دبي.",
    descriptionEN:
      "It is an exhibition space for innovative and futuristic ideologies, services and products. The Museum of the Future is located in the financial district of Dubai, and includes three main elements: the Green Hill, the building, and the void. The museum was founded by the Dubai Future Foundation, the government of the United Arab Emirates, inaugurated the museum on February 22, 2022. The date was officially chosen because February 22, 2022 is the date of Palindrome, the aim of this museum is to promote technological development and innovation, especially in the fields of artificial robotics. The museum is located in the Emirates Towers area near Sheikh Zayed Road in Dubai. The museum extends over an area of ​​30 thousand square meters and is 77 meters high, and consists of seven floors while it is fed by 4000 megawatts of electricity produced through solar energy, via a special station connected to the museum that was built in cooperation with the Dubai Electricity and Water Authority.",
    descriptionRU:
      "Это выставочное пространство для инновационных и футуристических идеологий, услуг и продуктов. Музей будущего расположен в финансовом районе Дубая и включает в себя три основных элемента: Зеленый холм, здание и пустоту. Музей был основан Dubai Future Foundation, правительством Объединенных Арабских Эмиратов, открытие музея состоялось 22 февраля 2022 года. Дата была официально выбрана, поскольку 22 февраля 2022 года является датой Палиндрома, целью этого музея является содействие технологическому развитию и инновациям, особенно в области искусственной робототехники. Музей расположен в районе Emirates Towers недалеко от шоссе шейха Зайда в Дубае. Музей занимает площадь 30 тысяч квадратных метров и имеет высоту 77 метров, состоит из семи этажей, при этом он питается 4000 мегаватт электроэнергии, вырабатываемой с помощью солнечной энергии, через специальную станцию, подключенную к музею, которая была построена в сотрудничестве с Управлением электроснабжения и водоснабжения Дубая.",
  },
  {
    nameAR: "القرية العالمية",
    url: "",
    nameEN: "The global village",
    nameRU: "Глобальная деревня",
    src: "/images/UAE/8.webp",
    descriptionAR:
      "تجمع ثقافات 90 دولة حول العالم في مكان واحد، وهي أكبر مشروع سياحي وترفيهي وتسوقي في العالم، وتعتبر الوجهة الثقافية والترفيهية والعائلية والتسوقية الأولى في المنطقة، وتستقبل سنوياً أكثر من 5 ملايين زائر لمساحة 17.2 مليون قدم مربع (1.6 مليون متر مربع). بدأت القرية العالمية كمجموعة من الأكشاك في يناير 1997، وتقع على جانب الخور مقابل بلدية دبي، ثم انتقلت إلى منطقة عود ميثاء بالقرب من مدينة وافي لمدة 5 سنوات، واليوم تستقبل القرية العالمية 6 ملايين زائر في موقعها الحالي عند مخرج شارع الشيخ زايد، وتتكون القرية من أربعة أقسام رئيسية، تتكون هذه الأقسام من الفعاليات والحفلات الموسيقية والغنائية والمأكولات والتسوق، وتحتوي ساحة الطعام على مأكولات من جميع أنحاء العالم. اختتمت القرية العالمية موسمها الـ27، الذي يعد موسمها الأكبر على الإطلاق، بعد أن سجلت رقماً قياسياً جديداً في عدد الضيوف، حيث وصل إلى 9 ملايين زائر منذ أن فتحت أبوابها في 25 أكتوبر 2022.",
    descriptionEN:
      "Bringing together the cultures of 90 countries around the world in one place, it is the largest tourism, entertainment and shopping project in the world. It is considered the first cultural, entertainment, family and shopping destination in the region. Every year, more than 5 million visitors to an area of ​​17,200,000 square feet (1,600,000 m2). The Global Village began as a number of kiosks in January 1997. It is located on the side of the creek opposite Dubai Municipality. It then moved to the Oud Metha area near Wafi City for 5 years. Today, the Global Village has 6 million visitors at its current location at the Sheikh Zayed Road exit. There are four main sections in the village. These sections consist of events, concerts, music, concerts, food and shopping. The food court contains food from all over the world. Global Village concluded its 27th season, which is its largest season ever, after recording a new record in the number of guests, reaching 9 million visitors since it opened its doors on October 25, 2022.",
    descriptionRU:
      "Объединяя в одном месте культуры 90 стран мира, это крупнейший в мире проект в сфере туризма, развлечений и шопинга. Он считается первым культурным, развлекательным, семейным и торговым направлением в регионе. Ежегодно более 5 миллионов посетителей посещают территорию площадью 17 200 000 квадратных футов (1 600 000 м2). Global Village начинался как ряд киосков в январе 1997 года. Он расположен на берегу ручья напротив муниципалитета Дубая. Затем он переехал в район Оуд Мета около города Вафи на 5 лет. Сегодня Global Village посещают 6 миллионов посетителей в его нынешнем месте на выезде с шоссе шейха Зайда. В деревне четыре основных раздела. Эти разделы состоят из мероприятий, концертов, музыки, концертов, еды и шопинга. Фуд-корт содержит еду со всего мира. Global Village завершил свой 27-й сезон, который стал самым масштабным за всю историю, установив новый рекорд по количеству гостей, достигнув 9 миллионов посетителей с момента открытия 25 октября 2022 года.",
  },
  {
    nameAR: "الحديقة المعجزة",
    url: "",
    nameEN: "miracle garden",
    nameRU: "Чудо-сад",
    src: "/images/UAE/9.webp",
    descriptionAR:
      "هي حديقة زهور تقع في منطقة دبي لاند، تم افتتاح الحديقة في عيد الحب عام 2013 بمساحة تزيد عن 72 ألف متر مربع، ما يجعلها أكبر حديقة زهور طبيعية في العالم، حيث تم زراعة أكثر من 150 مليون زهرة و120 نوعاً من الزهور، ويتم الحفاظ على الزهور من خلال إعادة استخدام المياه من خلال الري بالتنقيط بمتوسط ​​كمية مياه تصل إلى 757,082 لتراً يومياً، وفي عام 2015 تم افتتاح الحديقة في دبي، حديقة الفراشات في دبي، حيث تضم أكثر من 15 ألف فراشة من 26 نوعاً، ومن المعالم السياحية الأخرى في الحديقة ساعة الزهور، والطاووس، وحديقة الفراشات، والحديقة العطرية.",
    descriptionEN:
      "It is a flower garden located in the Dubai Land area. The garden was launched on Valentines Day in 2013 with an area of ​​more than 72,000 square meters, making it the largest natural flower garden in the world, with more than 150 million flowers planted and 120 types of flowers. The flowers are preserved by reusing water through drip irrigation with an average amount of 757,082 liters of water per day. In 2015, the garden opened in Dubai. The Dubai Butterfly Garden, with more than 15,000 butterflies of 26 species. Other attractions in the garden include the flower clock, the peacock, the butterfly garden, and the aromatic garden.",
    descriptionRU:
      "Это цветочный сад, расположенный в районе Dubai Land. Сад был запущен в День святого Валентина в 2013 году с площадью более 72 000 квадратных метров, что делает его крупнейшим естественным цветником в мире, с более чем 150 миллионами посаженных цветов и 120 видами цветов. Цветы сохраняются путем повторного использования воды с помощью капельного орошения со средним количеством 757 082 литров воды в день. В 2015 году сад открылся в Дубае. Дубайский сад бабочек с более чем 15 000 бабочек 26 видов. Другие достопримечательности в саду включают цветочные часы, павлина, сад бабочек и ароматический сад.",
  },
  {
    nameAR: "فنادق في د بي",
    url: "",
    nameEN: "Hotels in Dubai",
    nameRU: "Отели в Дубае",
  },
  {
    nameAR: "Four Seasons Resort Dubai at Jumeirah Beach",
    url: "",
    nameEN: "Four Seasons Resort Dubai at Jumeirah Beach",
    nameRU: "Four Seasons Resort Dubai at Jumeirah Beach",
    src: "/images/UAE/10.webp",
    descriptionAR:
      "يقع منتجع فور سيزونز دبي في جميرا بيتش المصنف 5 نجوم في قلب مدينة دبي، ويضم مسبحًا في الهواء الطلق وناديًا صحيًا. تشمل وسائل الراحة في الموقع منطقة شاطئ خاص ومطعمًا. يوجد 237 غرفة مكيفة في منتجع فور سيزونز دبي في جميرا بيتش الفاخر، بعضها مزود بنوافذ عازلة للصوت. كما يتوفر جاكوزي ودش مطري. يمكن للضيوف أيضًا الاستمتاع بإطلالات على البحر. في منتجع فور سيزونز دبي في جميرا بيتش المطل على الشاطئ، يمكنك الاستمتاع بالغطس والركض والتجديف بالكاياك. تشمل خيارات العافية في الموقع ناديًا صحيًا وصالة سبا، بالإضافة إلى علاجات التجميل. موقع الفندق",
    descriptionEN:
      "Located in the heart of Dubai, the 5-star Four Seasons Resort Dubai at Jumeirah Beach features an outdoor pool and a health club. On-site amenities include a private beach area and a restaurant. There are 237 air-conditioned rooms at the luxurious Four Seasons Resort Dubai at Jumeirah Beach, some with soundproof windows. A Jacuzzi and rain shower are also provided. Guests can also enjoy sea views. At the beachfront Four Seasons Resort Dubai at Jumeirah Beach, you can enjoy snorkeling, jogging and kayaking. On-site wellness options include a health club and a spa lounge, in addition to beauty treatments. Hotel website",
    descriptionRU:
      "Расположенный в самом сердце Дубая, 5-звездочный курорт Four Seasons Resort Dubai at Jumeirah Beach располагает открытым бассейном и оздоровительным клубом. Удобства на территории отеля включают частный пляж и ресторан. В роскошном курортном отеле Four Seasons Resort Dubai at Jumeirah Beach имеется 237 номеров с кондиционером, некоторые из которых оснащены звуконепроницаемыми окнами. Также предоставляются джакузи и тропический душ. Гости также могут насладиться видом на море. В прибрежном курортном отеле Four Seasons Resort Dubai at Jumeirah Beach вы можете заняться сноркелингом, бегом трусцой и покататься на байдарках. В оздоровительных центрах отеля есть оздоровительный клуб и спа-салон, а также косметические процедуры. Веб-сайт отеля",
  },
  {
    nameAR: "Bvlgari Resort Dubai",
    url: "",
    nameEN: "Bvlgari Resort Dubai",
    nameRU: "Bvlgari Resort Dubai",
    src: "/images/UAE/11.webp",
    descriptionAR:
      "خيارك المثالي عند زيارة دبي، حيث يوفر مزيجًا مثاليًا من القيمة والراحة، ويوفر أجواءً فاخرة مع العديد من وسائل الرفاهية التي يفضلها المسافرون. يقع فندق ومنتجع بولغاري دبي المطل على الخليج العربي في جميرا باي، وهي جزيرة على شكل فرس البحر على طول جسر يبلغ طوله 300 متر إلى الساحل المركزي لدبي. ويضم مرسى خاص به 50 رصيفًا وأول نادي يخت بولغاري في العالم بإطلالات لا مثيل لها على البحر. يقع مكان الإقامة على بعد 4.1 كم من دار الأوبرا في دبي.",
    descriptionEN:
      "Your ideal choice when visiting Dubai. Offering the perfect combination of value and comfort, it provides a luxurious atmosphere with many of the luxuries that travelers prefer. Overlooking the Arabian Gulf, Bulgari Hotel & Resorts, Dubai is located in Jumeirah Bay, a seahorse-shaped island along a 300-meter bridge to the central coast of Dubai. It has a private marina with 50 berths and the world`s first Bulgari Yacht Club with unparalleled sea views. The accommodation is located 4.1 km from Dubai Opera.",
    descriptionRU:
      "Ваш идеальный выбор при посещении Дубая. Предлагая идеальное сочетание цены и комфорта, он обеспечивает роскошную атмосферу со многими предметами роскоши, которые предпочитают путешественники. Bulgari Hotel & Resorts, Dubai с видом на Персидский залив расположен в заливе Джумейра, острове в форме морского конька вдоль 300-метрового моста к центральному побережью Дубая. Он имеет частную пристань для яхт с 50 причалами и первый в мире яхт-клуб Bulgari с непревзойденным видом на море. Размещение находится в 4,1 км от Дубайской оперы.",
  },
  {
    nameAR: "الشارقة",
    url: "",
    nameEN: "Sharjah",
    nameRU: "Шарджа",
    src: "/images/UAE/22.webp",
    descriptionAR:
      "إمارة من إمارات دولة الإمارات العربية المتحدة، أعلنت منظمة اليونسكو في عام 1988 الشارقة عاصمة للثقافة العربية، وأعلن وزراء الثقافة في الدول الإسلامية إمارة الشارقة عاصمة للثقافة الإسلامية لعام 2014، وتقديراً لإسهامات الشارقة في المشهد الثقافي المحلي والعربي، تم اختيار الشارقة للفوز بجائزة عاصمة السياحة العربية لعام 2015 خلال الدورة الخامسة عشرة لمجلس وزراء السياحة العرب بالقاهرة في 18 أكتوبر 2012، وتوصف بالعاصمة الثقافية لدولة الإمارات العربية المتحدة؛ حيث يوجد بها العديد من المعالم الأثرية والتاريخية، وتعد الشارقة ثالث أكبر إمارة من حيث المساحة، وتتميز بشواطئها الخلابة على جانبي الخليج العربي وخليج عمان، كما يوجد بالإمارة العديد من الأماكن الترفيهية التي أصبحت رمزاً لها على مدى السنوات الماضية، ويعود تاريخها إلى ستة آلاف عام، واعتمد الناس على التجارة وصناعة السفن البحرية بالإضافة إلى الزراعة وصيد الأسماك والبحث عن اللؤلؤ. استوطن السكان الأوائل حول الفلج أو مجرى الماء الذي حفره الإنسان.",
    descriptionEN:
      "An emirate of the United Arab Emirates, in 1988, UNESCO declared Sharjah the “Capital of Arab Culture”. The Ministers of Culture of the Islamic countries declared the Emirate of Sharjah the Capital of Islamic Culture for the year 2014. In recognition of Sharjah’s contributions to the local and Arab cultural scene, Sharjah was chosen to win the Arab Tourism Capital Award for the year 2015 during the 15th session of the Arab Tourism Ministers Council in Cairo on 􀟽 October 18, 2012. It is described as the cultural capital of the United Arab Emirates; Where there are many historical monuments and landmarks, Sharjah is the third largest emirate in terms of area, and is characterized by picturesque beaches on both sides of the Arabian Gulf and the Gulf of Oman. There are also many recreational places in the emirate that have become a symbol of it over the past years, dating back to six thousand years. People depended on trade and the manufacture of sea ships in addition to agriculture, fishing and searching for pearls. The first inhabitants settled around the falaj or the waterway made by man.",
    descriptionRU:
      "Эмират Объединенных Арабских Эмиратов, в 1988 году ЮНЕСКО объявила Шарджу «Столицей арабской культуры». Министры культуры исламских стран объявили эмират Шарджа столицей исламской культуры на 2014 год. В знак признания вклада Шарджи в местную и арабскую культурную жизнь Шарджа была выбрана победителем премии «Арабская столица туризма» за 2015 год на 15-й сессии Совета министров арабского туризма в Каире ܀�� 18 октября 2012 года. Ее называют культурной столицей Объединенных Арабских Эмиратов; где есть много исторических памятников и достопримечательностей, Шарджа является третьим по величине эмиратом по площади и характеризуется живописными пляжами по обе стороны Персидского залива и Оманского залива. В эмирате также есть много мест отдыха, которые стали его символом за последние годы, насчитывая шесть тысяч лет. Люди зависели от торговли и производства морских судов в дополнение к сельскому хозяйству, рыболовству и поиску жемчуга. Первые жители поселились вокруг фаладжа или водного пути, созданного человеком.",
  },
  {
    nameAR: "جامع النور",
    url: "",
    nameEN: "Al Noor Mosque",
    nameRU: "Мечеть Аль-Нур",
    src: "/images/UAE/23.webp",
    descriptionAR:
      "هو مسجد بني على الطراز العثماني ويطل على بحيرة خالد ويتميز بقبابه المتعددة ويعتبر المبنى من روائع العمارة الإماراتية حيث يحتوي على نقوش وزخارف خارج وداخل المسجد على أعمدته ومئذنتين شاهقتين في زوايا المبنى وقبة كبيرة تتوسط أعلى المسجد محاطة بنوافذ مبطنة بالزجاج الملون ويتمتع المسجد بموقع مثالي يعتبر من أشهر مناطق الإمارة وأكثرها حيوية على شارع الكورنيش وتحديداً في أشهر مناطق الإمارة وأكثرها حيوية.",
    descriptionEN:
      "It is a mosque built in the Ottoman style and overlooks Khalid Lake. It is distinguished by its multiple domes. The building is considered one of the Emirati architectural masterpieces, as it contains engravings and decorations outside and inside the mosque on its columns, two towering minarets on the corners of the building, and a large dome in the middle of the top of the mosque surrounded by windows lined with stained glass. The mosque enjoys an ideal location, which is considered one of the most famous and lively areas of the emirate on the Corniche Street, specifically in the most famous and lively areas of the emirate.",
    descriptionRU:
      "Это мечеть, построенная в османском стиле и возвышающаяся над озером Халид. Она отличается своими многочисленными куполами. Здание считается одним из шедевров архитектуры Эмиратов, поскольку содержит гравюры и украшения снаружи и внутри мечети на ее колоннах, два возвышающихся минарета по углам здания и большой купол в середине верхней части мечети, окруженный окнами, облицованными витражами. Мечеть имеет идеальное расположение, которое считается одним из самых известных и оживленных районов эмирата на улице Корниш, особенно в самых известных и оживленных районах эмирата.",
  },
  {
    nameAR: "قناة القصباء",
    url: "",
    nameEN: "Al Qasba Channel",
    nameRU: "Канал Аль-Касба",
    src: "/images/UAE/24.webp",
    descriptionAR:
      "وهو ممر مائي يقدر طوله بحوالي كيلومتر، ويضم على جانبيه العديد من المرافق السياحية من مطاعم ومقاهي راقية تجسد إبداعات التراث والعمارة الحديثة، بالإضافة إلى ألعاب متنوعة للأطفال، ويستضيف مسرح القصباء الذي يتسع لـ 300 شخص عروضاً موسيقية وغنائية ومسرحيات متنوعة، بالإضافة إلى إقامة معارض وفعاليات متنوعة تنظمها المؤسسات، على مساحة 1500 متر مربع مخصصة لهذا الغرض. ويعد ممر القصباء المائي أحد أهم المعالم السياحية والثقافية في إمارة الشارقة، ويربط بين بحيرة خالد وبحيرة الخان بطول كيلومتر واحد.",
    descriptionEN:
      "It is a waterway estimated to be about a kilometer long, and includes on both sides many tourist facilities from upscale restaurants and cafes that embody the creativity of heritage and modern architecture, as well as various games for children. Al Qasba Theater, which can accommodate 300 people, hosts musical and singing performances and various plays, in addition to holding various exhibitions and events organized by institutions, on an area of ​​1500 square meters dedicated to this purpose. Al Qasba Waterway is one of the most important tourist and cultural landmarks in the Emirate of Sharjah, and connects Khalid Lake and Al Khan Lake with a length of one kilometer.",
    descriptionRU:
      "Это водный путь, длина которого оценивается примерно в километр, и включает в себя по обе стороны множество туристических объектов от высококлассных ресторанов и кафе, которые воплощают креативность наследия и современной архитектуры, а также различные игры для детей. Театр Аль-Касба, который может вместить 300 человек, проводит музыкальные и вокальные представления и различные пьесы, в дополнение к проведению различных выставок и мероприятий, организованных учреждениями, на площади в 1500 квадратных метров, выделенной для этой цели. Водный путь Аль-Касба является одной из важнейших туристических и культурных достопримечательностей в эмирате Шарджа и соединяет озеро Халид и озеро Аль-Хан длиной в один километр.",
  },

  {
    nameAR: "متحف الشارقة الإسلامي",
    url: "",
    nameEN: "Sharjah Islamic Museum",
    nameRU: "Исламский музей Шарджи",
    src: "/images/UAE/25.webp",
    descriptionAR:
      "افتتح لأول مرة في منطقة التراث بالشارقة عام 1996، وتم نقل المتحف المميز إلى مبنى السوق، حيث تمت إضافة مجموعات جديدة وتحديث أسلوب العرض في المتحف. أعيد افتتاح متحف الشارقة للحضارة الإسلامية في 6 يونيو 2008، ويضم سبع قاعات عرض مقسمة إلى طابقين. تعرض قاعات العرض في الطابق الأرضي جوانب من العقيدة الإسلامية وإنجازات العلماء والفلكيين العرب، بينما يقدم الطابق العلوي رواية تاريخية للفنون والحرف الإسلامية، بما في ذلك المنسوجات والمجوهرات. يقع المتحف في مبنى مميز، ومميز مثل معروضاته، على كورنيش الشارقة، شمال منطقة قلب الشارقة مباشرة. تتنافس جميع المعروضات على جذب انتباهك، من الخط والمخطوطات إلى الخزف والعملات، ولكن لا تفوت فرصة رؤية الستارة المطرزة بالذهب لباب الكعبة المشرفة، والزخارف الفسيفسائية المذهلة داخل القبة المركزية التي تُظهر السماء الليلية والبروج.",
    descriptionEN:
      "It was first opened in the Heritage Area of ​​Sharjah in 1996. The distinctive museum was moved to the Souq building, where new collections were added and the display style in the museum was updated. Reopened as the Sharjah Museum of Islamic Civilization on June 6, 2008, the Sharjah Museum of Islamic Civilization houses seven exhibition halls divided into two floors. The exhibition halls on the ground floor display aspects of the Islamic faith and the achievements of Arab scientists and astronomers, while the upper floor presents a historical account of Islamic arts and crafts, including textiles and jewelry. The museum is located in a distinctive building, as distinctive as its exhibits, on the Sharjah Corniche, just north of the Heart of Sharjah area. All the exhibits compete for your attention, from calligraphy and manuscripts to ceramics and coins, but don`t miss the opportunity to see the gold-embroidered curtain of the door of the Holy Kaaba, and the stunning mosaic decoration inside the central dome that shows the night sky and the zodiac.",
    descriptionRU:
      "Впервые он был открыт в районе наследия Шарджи в 1996 году. Этот своеобразный музей был перемещен в здание Souq, где были добавлены новые коллекции и обновлен стиль экспозиции музея. Вновь открытый как Музей исламской цивилизации Шарджи 6 июня 2008 года, Музей исламской цивилизации Шарджи вмещает семь выставочных залов, разделенных на два этажа. Выставочные залы на первом этаже демонстрируют аспекты исламской веры и достижения арабских ученых и астрономов, в то время как на верхнем этаже представлен исторический отчет об исламском искусстве и ремеслах, включая текстиль и ювелирные изделия. Музей расположен в своеобразном здании, столь же своеобразном, как и его экспонаты, на набережной Шарджи, к северу от района Heart of Sharjah. Все экспонаты соревнуются за ваше внимание: от каллиграфии и рукописей до керамики и монет, но не упустите возможность увидеть расшитую золотом завесу двери Священной Каабы и потрясающую мозаичную отделку внутри центрального купола, изображающую ночное небо и знаки зодиака.",
  },
  {
    nameAR: "شاطئ خورفكّان",
    url: "",
    nameEN: "Khorfakkan Beach",
    nameRU: "Пляж Хор Факкан",
    src: "/images/UAE/26.webp",
    descriptionAR:
      "ويهدف مشروع شاطئ خورفكان إلى إعادة تصميم الشاطئ الذي يبلغ طوله 3 كيلومترات بإضافة مرافق عامة عالية الجودة ومجموعة مميزة من الأنشطة الترفيهية والسياحية وخيارات متنوعة لتناول الطعام والضيافة من شأنها أن تعزز بشكل كبير من نمط حياة السكان والزوار على حد سواء. وتوفر سواحل الشارقة الشرقية والغربية فرصاً ممتازة لممارسة رياضة التجديف بالكاياك، ومن أشهر أماكن ممارسة رياضة التجديف شاطئ الخان وشاطئ خورفكان وأشجار القرم في خور كلباء، وتأتي القوارب هناك بأشكال وأحجام متنوعة، وعند الاقتراب من حافة الجبل يمكنهم الاستمتاع بالمياه الطبيعية القريبة ومشاهدة الأسماك أو الغزلان التي تجوب البحيرة أو أنواع الطيور المختلفة التي تلجأ إلى البحيرة.",
    descriptionEN:
      "The Khorfakkan Beach Project aims to redesign the 3-kilometre-long beach by adding high-quality public facilities, a distinctive range of recreational and tourist activities, and a variety of dining and hospitality options that will greatly enhance the lifestyle of residents and visitors alike. Sharjah’s eastern and western coasts offer excellent opportunities for kayaking. The most famous kayaking spots are Al Khan Beach, Khorfakkan Beach and the mangroves of Khor Kalba. The boats there come in a variety of shapes and sizes. When approaching the edge of the mountain, they can enjoy the nearby natural water and watch the fish 􀟾 see the gazelles roaming the lake or the various types of birds that take refuge in the lake.",
    descriptionRU:
      "Проект пляжа Корфаккан направлен на перепланировку 3-километрового пляжа путем добавления высококачественных общественных объектов, особого спектра развлекательных и туристических мероприятий, а также разнообразных вариантов питания и гостеприимства, которые значительно улучшат образ жизни жителей и гостей. Восточное и западное побережья Шарджи предлагают прекрасные возможности для каякинга. Самые известные места для каякинга — пляжи Аль-Хан, Корфаккан и мангровые заросли Хор-Калба. Лодки там бывают разных форм и размеров. Приближаясь к краю горы, можно насладиться близлежащей природной водой и понаблюдать за рыбой, увидеть газелей, бродящих по озеру, или различные виды птиц, которые укрываются в озере.",
  },
  {
    nameAR: "مركز مليحة للآثار",
    url: "",
    nameEN: "Mleiha Archaeological Centre",
    nameRU: "Археологический центр Млейха",
    src: "/images/UAE/27.webp",
    descriptionAR:
      "يعد مركز مليحة الأثري أحد أهم المواقع التاريخية الطبيعية في المنطقة، ومن هنا ستنطلق في جولة مثيرة لموقع يعود تاريخه إلى 130 ألف عام خلال العصر الحجري القديم، لتشاهد بنفسك كيف عاش البشر الأوائل في مليحة. وعلى مسافة قصيرة، تنتظر جميع المغامرين الباحثين عن الإثارة دراجات رباعية الدفع بقوة 1000 سي سي. يوفر هذا الموقع العديد من المرافق الفريدة للزوار، بما في ذلك جولات الدراجات الصحراوية، ومغامرات الطرق الوعرة المثيرة، وركوب الخيل. لا شك أن وجهة مثل هذه تزيد من تقدير أسلوب الحياة العربي وتاريخه القديم. يقع المركز في مليحة بالقرب من جبل فايح، على بعد 65 كم جنوب شرق مدينة الشارقة. انطلق في مغامرات صحراوية من خلال مجموعة من الأنشطة المتاحة، بما في ذلك الجولات ورحلات الدفع الرباعي إلى صخرة حافور وصخرة الجمل، واستقل المظلة من أعلى تلال مليحة وعش تجربة استثنائية في ركوب الدراجات الصحراوية وركوب الدراجات على الكثبان الرملية والتخييم بين عشية وضحاها.",
    descriptionEN:
      "The Mleiha Archaeological Center is one of the most important natural historical sites in the region, and from here you will embark on an exciting tour of a site dating back 130,000 years during the Paleolithic era, to see for yourself how the first humans lived in Mleiha . A short distance away, quad bikes with a power of 1000 cc await all adventurers looking for a thrill. This site offers many unique facilities for visitors, including desert bike tours, exciting off-road adventures, and horse riding. There is no doubt that a destination like this increases appreciation for the Arab way of life and its ancient history. The center is located in Mleiha near Jebel Fayeh, 65 km southeast of Sharjah city. Embark on desert adventures through a range of activities available, including tours and 4WD trips to the Hafoor Rock and Camel Rock, and take a parachute from the tallest hills of Mleiha and live an exceptional experience in desert biking, dune biking and overnight camping.",
    descriptionRU:
      "Археологический центр Млейха является одним из важнейших природных исторических памятников в регионе, и отсюда вы отправитесь в захватывающую экскурсию по месту, возраст которого составляет 130 000 лет в эпоху палеолита, чтобы увидеть своими глазами, как жили первые люди в Млейхе. Неподалеку от него квадроциклы с мощностью 1000 куб. см ждут всех искателей приключений, ищущих острых ощущений. Этот объект предлагает множество уникальных удобств для посетителей, включая туры на велосипедах по пустыне, захватывающие приключения по бездорожью и верховую езду. Нет сомнений, что такое место назначения повышает оценку арабского образа жизни и его древней истории. Центр расположен в Млейхе недалеко от Джебель-Файе, в 65 км к юго-востоку от города Шарджа. Отправьтесь в приключения в пустыне, выбрав один из множества вариантов досуга, включая туры и поездки на внедорожниках к скалам Хафур и Кэмел, а также прыгните с парашютом с самых высоких холмов Млейхи и получите исключительные впечатления от катания на велосипеде по пустыне, дюнам и ночевки в кемпинге.",
  },
  {
    nameAR: "فنادق في الشارقة",
    url: "",
    nameEN: "Hotels in Sharjah",
    nameRU: "Отели в Шардже",
  },
  {
    nameAR: "Sheraton Sharjah Beach Resort and Spa",
    url: "",
    nameEN: "Sheraton Sharjah Beach Resort and Spa",
    nameRU: "Sheraton Sharjah Beach Resort and Spa",
    src: "/images/UAE/30.webp",
    descriptionAR:
      "يقع منتجع شيراتون الشارقة بيتش على بعد 10 كم من أكواريوم الشارقة و12 كم من مركز صحارى، ويضم منطقة شاطئية خاصة. يقع مكان الإقامة هذا بالقرب من مناطق الجذب السياحي مثل متحف الحضارة الإسلامية، ويضم مسبحًا في الهواء الطلق. يقع متحف الشارقة للتراث على بعد 6 كم من مكان الإقامة.",
    descriptionEN:
      "Located 10 km from Sharjah Aquarium and 12 km from Sahara Centre, Sheraton Sharjah Beach Resort features a private beach area. Featuring an outdoor pool, this accommodation is close to attractions such as Museum of Islamic Civilization. Sharjah Heritage Museum is 6 km from the accommodation.",
    descriptionRU:
      "Курортный отель Sheraton Sharjah Beach расположен в 10 км от аквариума Шарджи и в 12 км от торгового центра Sahara Centre. К услугам гостей открытый бассейн и частный пляж. Отель находится недалеко от таких достопримечательностей, как Музей исламской цивилизации. Расстояние до Музея наследия Шарджи составляет 6 км.",
  },
  {
    nameAR: "The Chedi Al Bait, Sharjah - a GHM hotel",
    url: "",
    nameEN: "The Chedi Al Bait, Sharjah - a GHM hotel",
    nameRU: "The Chedi Al Bait, Sharjah - a GHM hotel",
    src: "/images/UAE/31.webp",
    descriptionAR:
      "يقع الفندق على بعد 3.9 كم من أكواريوم الشارقة، ويتميز بإطلالات على المدينة. ويضم مكتب استقبال يعمل على مدار 24 ساعة ومطعم ومسبح خارجي. ويضم المنتجع مركزًا للياقة البدنية ومركزًا لرجال الأعمال. يقع مركز صحارى على بعد 7 كم من Al Bait Sharm El Sheikh، في حين يقع متحف الشارقة للتراث على بعد 200 م من مكان الإقامة. ويعتبر مطار دبي الدولي المطار الأقرب لـ Al Bait Sharm El Sheikh حيث يقع على بعد 12 كم منه.",
    descriptionEN:
      "Located 3.9 km from Sharjah Aquarium, the hotel features city views. It features a 24-hour front desk, a restaurant and an outdoor pool. The resort features a fitness centre and a business centre. Sahara Centre is 7 km from Al Bait Sharjah, while Sharjah Heritage Museum is 200 metres from the accommodation. The nearest airport is Dubai International Airport, 12 km from Al Bait Sharjah",
    descriptionRU:
      "Отель расположен в 3,9 км от аквариума Шарджи. Из окон открывается вид на город. К услугам гостей круглосуточная стойка регистрации, ресторан и открытый бассейн. На территории курортного отеля есть фитнес-центр и бизнес-центр. Торговый центр Sahara Centre находится в 7 км от отеля Al Bait Sharjah, а Музей культурного наследия Шарджи — в 200 метрах. Расстояние от отеля Al Bait Sharjah до международного аэропорта Дубая составляет 12 км.",
  },
];
